# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171024_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banned',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
