# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='version',
            field=models.CharField(default=0, editable=False, max_length=200),
        ),
    ]
