# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
